### PR TITLE
Add a GitHub Action link

### PR DESCRIPTION
**Pull request by gingerhot**
@lannonbr Add a GitHub Action link of issue tracker in general.

### CODE REVIEW

**Comment by lannonbr** [comment]
It doesn't look like actioncloud.io is live so I don't want to possibly merge this in until things are fully functional

**Comment by gingerhot** [comment]
Now all actioncloud apps are hosted under the subdomain [free.actioncloud.io](https://free.actioncloud.io) on GitHub pages, the free.actioncloud.io is live as long as the GitHub pages work.  And also:

1. issue-tracker-action's viewer page is under [the folder ](https://github.com/actioncloud/actioncloud.github.io/tree/master/apps/github-issue-tracker)
2. the page can be visited, e.g. we can view this action repo's data: https://free.actioncloud.io/apps/github-issue-tracker/?owner=actioncloud&repo=issue-tracker-action

Thank you again for your issue tracker, and I think that's a nice tool that can be used by more people through the GitHub Action, and we are working on more such actions at actioncloud.

**Comment by lannonbr** [comment]
None of those pages are loading for me for some reason

**Comment by gingerhot** [comment]
I've tested all these links after I pasted them here, anyway I'm sorry for not working for you and took your time to try it. Thanks again~

**Pull request closed without merging**
